Pchelkina (6231)
itsecd/ml-for-sec-lab1 pull request #2
Opened 2022-09-28 16:18 UTC by YuliyaPchelkina

Выполнены 1 и 2 варианты задания

2022-10-26 22:28 UTC, vicanfed requested changes
Всё отлично, почти выполнены аж три задания, проведено объёмное исследование!
Модель обеспечивает идеальную точность на моей выборке.
Но некоторые правки нужны во все части. Основная причина - нет трёх разных моделей, обученных в трёх разных условиях.

sns.heatmap(df.corr(), cmap = "mako")
полезнее было бы построить по df1 - корреляцию с ответами можно было бы посмотреть.

DecisionTreeClassifier,RandomForestClassifier вроде как не требуют нормализации признаков.

для более качественного обучения моделей Cross validation лучше было бы сделать (просто совет)

list1 = np.vstack([importance, attribute]).T - ненужная строка?

В итоге в 1.1 выбрана линейная регрессия. Но в файл модель не сохраняется. А сохраняемая в конце модель имеет другое имя и расширение. Так какая модель сохранена?

Отличный вариант поиска значимости признаков на основе регрессии! Но! importance = model.coef_ - неправильный вариант, поскольку большие по модулю отрицательные коэффициенты как раз говорят о высоком влиянии признака. И ещё одно важное но: для оценки значимости признаков их надо нормировать перед обучением регрессионной модели.
Вот статья на эту тему https://statisticsbyjim.com/regression/identifying-important-independent-variables/

sel_best = best_features1.nlargest(K, 'chi2_score') при этом K равно числу признаков
# Отбираем лучшие по обоим методам - реально там попадаются все, а десятка искомая выходит рандомно

2.1 - нет выбора итоговой модели и её сохранения

# Работаем с наиболее "информативными" признаками - зря, это же уже ограничивает модель

def Metrics (conf_mat): несколько избыточная функция: у нас всего два класса

2.2 - модель не сохранена, но сохраняется другая переученная заново модель по выбранным гиперпараметрам. Строго говоря, соблюдение ограничения на FN новая модель не гарантирует.

Многовато коммитов с небольшими изменениями. Не стоит ли в целом их реже делать?

2022-10-27 15:10 UTC, YuliyaPchelkina commented
Все исправлено согласно замечаниям. Файл Lab1(new).ipynb

2022-10-28 21:33 UTC, vicanfed requested changes
Всё поправлено и улучшено. Но файл с использованием классификатора и собственно процедура classify yt отлажены для всех случаев. При необходимости можно сделать две функции - classify1 и classify2

1
В 1.1 модель на моей тестовой выборке очень плохо работает. Я думаю, scaler.transform не делается в classify. Либо надо дампить модель вместе со scaler-ом, либо ввыбирать модель без нормировки.  

2
Просто непонятно: а почему в 2.1 kNN был выбран? Можно устно потом обсудить
Но важнее другое: применении 2.1 в методе classify ошибка: ValueError: X has 20 features, but KNeighborsClassifier is expecting 10 features as input.

2022-10-31 08:37 UTC, YuliyaPchelkina commented
1 Классификатор поправила, добавила нормировку для регрессии.

2.1 Попробовала и другие модели. в итоге выбран не KNN. Сохранила модель, обученную на полном наборе

2022-10-31 12:43 UTC, vicanfed approved these changes

2022-12-12 08:22 UTC, closed without merging